Prepare for release v5.0.1
voxpupuli/puppet-smokeping pull request #127
Opened 2020-09-23 09:34 UTC by andybotting

2020-09-23 16:21 UTC, igalic requested changes
🙋🏻‍♀️

2020-09-23 16:21 UTC, igalic commented on metadata.json
> +  "version": "5.0.1",
unless this release was literally a single bug fix, i'd bump the version to 5.1.0

2020-09-23 21:36 UTC, andybotting commented on metadata.json
> +  "version": "5.0.1",
Updated now to use v5.1.0

2020-09-24 04:14 UTC, igalic approved these changes

2020-09-24 04:34 UTC, andybotting commented
:tada:

2020-09-24 07:40 UTC, merged

2020-09-24 07:46 UTC, andybotting commented
Thanks!

2020-09-24 07:47 UTC, igalic commented
released 5.1.0 https://forge.puppet.com/puppet/smokeping/readme